AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - contrib/**/*
    - config/**/*
    - db/**/*
    - node_modules/**/*
    - tmp/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - Capfile
    - Gemfile
    - Rakefile
    - config.ru

Style/MethodCallWithArgsParentheses:
  Exclude:
    - spec/**/*

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

require: rubocop-rspec

inherit_from:
  - .rubocop-https---shopify-github-io-ruby-style-guide-rubocop-yml
